version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/migrations:/docker-entrypoint-initdb.d
    networks:
      - todo-network

  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile for gRPC server is in the root
    ports:
      - "50051:50051"
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - todo-network

  api-gateway:
    build:
      context: .
      dockerfile: ./cmd/gateway/Dockerfile # Dockerfile for API Gateway is in cmd/gateway/
    ports:
      - "8080:8080"
    depends_on:
      - grpc-server
    env_file:
      - .env
    networks:
      - todo-network

volumes:
  mysql-data:

networks:
  todo-network:
    driver: bridge

