version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/migrations:/docker-entrypoint-initdb.d

  grpc-server:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - mysql
    env_file:
      - .env

volumes:
  mysql-data:

